//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtorApp.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public Listing()
        {
            this.ListingImages = new HashSet<ListingImage>();
        }
    
        public int MLS { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Zipcode { get; set; }
        public string Neighborhood { get; set; }
        public decimal SalesPrice { get; set; }
        public System.DateTime DateListed { get; set; }
        public int Bedrooms { get; set; }
        public double Bathrooms { get; set; }
        public Nullable<double> GarageSize { get; set; }
        public int SquareFeet { get; set; }
        public string LotSize { get; set; }
        public string Description { get; set; }
        public int ListingID { get; set; }
    
        public virtual ICollection<ListingImage> ListingImages { get; set; }
    }
}
