//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtorApp.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingImage
    {
        public int ListingID { get; set; }
        public string ImageName { get; set; }
        public int ListingImageID { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
