CREATE USER [RealtorAppMLSUser]
	FOR LOGIN RealtorAppMLSUser
	WITH DEFAULT_SCHEMA = dbo

GO

GRANT CONNECT TO [RealtorAppMLSUser]
GO
GRANT CREATE TABLE TO [RealtorAppMLSUser]
GO
GRANT UPDATE ON SCHEMA :: dbo TO [RealtorAppMLSUser]
GO
GRANT SELECT ON SCHEMA :: dbo TO [RealtorAppMLSUser]
GO
GRANT EXECUTE ON SCHEMA :: dbo TO [RealtorAppMLSUser]
GO
GRANT INSERT ON SCHEMA :: dbo TO [RealtorAppMLSUser]
GO
GRANT VIEW DEFINITION ON SCHEMA :: dbo TO [RealtorAppMLSUser]
GO
GRANT CONTROL ON SCHEMA :: dbo TO [RealtorAppMLSUser]
GO
GRANT ALTER ON SCHEMA :: dbo TO [RealtorAppMLSUser]
GO